[package]
name = "ckb-sdk"
version = "1.0.0"
authors = ["Linfeng Qian <thewawar@gmail.com>", "Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"
description = "Rust SDK for CKB"
homepage = "https://github.com/cryptape/ckb-sdk"
repository = "https://github.com/cryptape/ckb-sdk"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
thiserror = "1.0.30"
bech32 = "0.8.1"
log = "0.4.6"
reqwest = { version = "0.11", features = ["json", "blocking"] }
secp256k1 = { version = "0.20", features = ["recovery"] }
faster-hex = "0.6"
byteorder = "1.3.2"
bitcoin_hashes = "0.3.2"
tokio-util = { version = "0.6", features = ["codec"] }
tokio = { version = "1" }
bytes = "1"
futures = "0.3"
jsonrpc-core = "18"
parking_lot = "0.11"
lru = "0.7.1"

ckb-types = "=0.103.0"
ckb-dao-utils = "=0.103.0"
ckb-traits = "=0.103.0"
ckb-jsonrpc-types = "=0.103.0"
ckb-hash = "=0.103.0"
ckb-resource = "=0.103.0"
ckb-crypto = { version = "=0.103.0", features = ["secp"] }

[dev-dependencies]
clap = { version = "3.1.9", features = ["derive"] }