[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "deny"
notice = "deny"
ignore = []

[licenses]
unlicensed = "deny"
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
    "Unicode-DFS-2016",
    "BSL-1.0", # xxhash-rust 0.8.10
]
copyleft = "deny"
default = "deny"
exceptions = [
    { allow = ["MPL-2.0"], name = "colored", version = "*" },
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
